### ISSUE TITLE
Configurable shortcut for "run selected line(s)"

### ISSUE THREAD

**Issue by milosivanovic** [jshinonome/vscode-q#30]
Hello,

Thank you for creating this wonderful extension! I was wondering if you would consider adding a configurable shortcut for at least the "run selected line(s)" command:

<img width="475" alt="Screen Shot 2021-03-15 at 1 27 58 AM" src="https://user-images.githubusercontent.com/1274505/111068462-ae58a680-852d-11eb-9321-5545f3942f4f.png">

I used qStudio for a long time which uses CTRL+E (CMD+E on macOS), and there is another vscode extension https://github.com/real-xidaozu/vscode-kdb-q that follows this tradition. It would be helpful for any users who prefer to keep using their muscle memory.

If it is already possible to configure shortcuts for these, would you mind pointing me in the right direction to do that? :)

Also, two more related things:
1. I think it might be helpful to clarify that it's actually "run selection" rather than "run selected line(s)" since you can query a part of a line with that command.
2. Users of macOS generally use CMD in place of CTRL. This looks to conflict with some of the current shortcuts (like CTRL+Q), since CMD+Q will quit an application entirely on macOS! If users can eventually choose their own shortcuts they could fix that themselves, however I think it would be useful to choose default mappings that work well cross-platform.

Thanks again for your time.

**Comment by jshinonome** [comment]
Hello, thanks for your advice. 
1. You can change the shortcut to anything you want. I didn't use ctrl+e, because I don't want to overwrite the existing shortcut. To change the shortcut, 
- macOS: open keymap by `command k command s`, and search for "kdb".
- other: `ctrl+shift+p`, search for "shortcut", on the "keymap shortcurt", search for "kdb"
2. Exactly, I will change to "selection" in the next release.
Hope you enjoy this extension.

**Comment by milosivanovic** [comment]
Thank you, sorry I didn't know it was already mapped. It seems like there are so many shortcuts already that it would be hard not to overwrite one eventually... even on macOS CTRL+R already did something (never used it myself):

<img width="1034" alt="Screen Shot 2021-03-15 at 1 54 28 PM" src="https://user-images.githubusercontent.com/1274505/111090885-0c20d900-8596-11eb-9548-16194eb4d84d.png">

Anyway, since it's possible to remap these keys easily then I will close this issue.

Regarding how to access the Keyboard Shortcuts interface in vscode: generally, the key combinations are the same on every platform except the modifier key is often CMD on macOS. So for example, you open the Command Palette on macOS with CMD+SHIFT+P (instead of CTRL+SHIFT+P), search for "shortcut" and open the Keyboard Shortcuts interface as you'd expect. CMD+K and CMD+S also work, just like CTRL+K and CTRL+S would be how you would open it on Windows/Linux.

Somehow vscode knows to switch (most?) CTRL shortcuts to CMD automatically on a macOS install, but it did not do that for the vscode-q extension. I guess what I am saying is I would have thought I could access vscode-q's CTRL shortcuts with CMD, but it seems like this remapping does not in fact occur automatically. Any thoughts on how that works?

In any case, I appreciate the quick follow-up and overall my main concern has been addressed! :)

**Comment by jshinonome** [comment]
Hi Milos,
I guess you are synchronizing your configuration with github. About automatically switching ctrl to cmd, sorry that there is nothing I can do. You can raise this with vscode repo see if they can help. Otherwise, I would recommend you not to synchronizing this configuration but set up separately on different OSs.
